line_length:
  warning: 200
  error: 400
  ignores_urls: true
  ignores_comments: true
  ignores_interpolated_strings: true

# MARK: - Code Safety & Bugs
force_cast: warning          # Avoid crashes
force_try: warning           # Avoid runtime crashes
implicitly_unwrapped_optional: warning
fatal_error_message: warning # Enforce meaningful messages

# MARK: - Optional Handling
empty_count: warning         # Prefer `isEmpty` over `count == 0`
optional_enum_case_matching: warning
implicit_optional_initialization: warning

# MARK: - Memory Management
weak_delegate: warning       # Prevent retain cycles
strong_iboutlet: warning     # IBOutlets should usually be weak

# MARK: - Swift Best Practices
array_init: warning          # Prefer shorthand array initialization
contains_over_filter_count: warning
first_where: warning
last_where: warning
reduce_into: warning
toggle_bool: warning
sorted_first_last: warning

# MARK: - Performance
unused_closure_parameter: warning
unused_optional_binding: warning
unused_import: warning

# MARK: - Code Clarity
explicit_init: warning
redundant_type_annotation: warning
redundant_void_return: warning
shorthand_operator: warning
vertical_whitespace: warning

# MARK: - Style (Readable, Not Pedantic)
trailing_whitespace:
  ignores_empty_lines: true
  ignores_comments: true

multiline_arguments:
  first_argument_location: next_line
  only_enforce_after_first_closure_on_first_line: true

# MARK: - Naming
identifier_name:
  min_length:
    warning: 2
  max_length:
    warning: 60
  excluded:
    - id
    - x
    - y
    - z

type_name:
  min_length: 3
  max_length:
    warning: 50

# MARK: - Control Flow
empty_enum_arguments: warning
fallthrough: warning
for_where: warning
switch_case_alignment: warning

# MARK: - Opt-in Rules (required for the rules above to take effect)
opt_in_rules:
  - array_init
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - empty_count
  - implicit_optional_initialization
  - implicitly_unwrapped_optional
  - fallthrough
  - multiline_arguments
  - explicit_init
  - fatal_error_message
  - first_where
  - last_where
  - optional_enum_case_matching
  - reduce_into
  - sorted_first_last
  - strong_iboutlet
  - toggle_bool
  - weak_delegate
  - redundant_nil_coalescing
  - contains_over_first_not_nil
  - redundant_type_annotation

analyzer_rules:
  - unused_import
